apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tines.fullname" . }}-app
  labels:
    {{- include "tines.labels" . | nindent 4 }}
spec:
  replicas: {{ if not (kindIs "invalid" .Values.replicaCount) }}{{ .Values.replicaCount }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      {{- include "tines.selectorLabels" . | nindent 6 }}
      component: app
  template:
    metadata:
      labels:
        {{- include "tines.selectorLabels" . | nindent 8 }}
        component: app
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: RAILS_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "tines.fullname" . }}-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.auth.database }}"
            - name: REDIS_URL
              value: "redis://{{ include "tines.fullname" . }}-redis:{{ .Values.redis.port }}/0"
            - name: APP_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tines-app-config
                  key: SECRET_KEY_BASE
            - name: TINES_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: tines-app-config
                  key: TINES_ENCRYPTION_KEY
            - name: TENANT_NAME
              value: {{ .Values.global.tenantName | quote }}
            - name: DOMAIN
              value: "localhost:3000"
          # Liveness and readiness probes would go here
