apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tines.fullname" . }}-migration
  labels:
    {{- include "tines.labels" . | nindent 4 }}
    component: migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "tines.selectorLabels" . | nindent 8 }}
        component: migration
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-migration
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "rails", "db:prepare"]
          env:
            - name: RAILS_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "tines.fullname" . }}-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.auth.database }}"
            - name: REDIS_URL
              value: "redis://{{ include "tines.fullname" . }}-redis:{{ .Values.redis.port }}/0"
            - name: APP_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tines-app-config
                  key: SECRET_KEY_BASE
            - name: TINES_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: tines-app-config
                  key: TINES_ENCRYPTION_KEY
            - name: TENANT_NAME
              value: {{ .Values.global.tenantName | quote }}
