apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tines.fullname" . }}-sidekiq
  labels:
    {{- include "tines.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sidekiq.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "tines.selectorLabels" . | nindent 6 }}
      component: sidekiq
  template:
    metadata:
      labels:
        {{- include "tines.selectorLabels" . | nindent 8 }}
        component: sidekiq
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-sidekiq
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"] 
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "tines.fullname" . }}-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.auth.database }}"
            - name: REDIS_URL
              value: "redis://{{ include "tines.fullname" . }}-redis:{{ .Values.redis.port }}/0"
            - name: RAILS_ENV
              value: "production"
            - name: APP_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tines-app-config
                  key: SECRET_KEY_BASE
            - name: TINES_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: tines-app-config
                  key: TINES_ENCRYPTION_KEY
            - name: TENANT_NAME
              value: {{ .Values.global.tenantName | quote }}
